<?php
$baseUrl = $this->baseUrl();
?>
<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/css/admin_style1.css" type="text/css" media="screen" />
<script src="<?php echo $this->baseUrl()?>/js/tiny_mce/tiny_mce.js" type="text/javascript" ></script>
<script type="text/javascript">
tinyMCE.init({
    theme : "advanced",
	mode : "textareas",
	skin : "o2k7",
	skin_variant : "silver",
	plugins : "table",
	theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,tablecontrols,|,outdent,indent,|,undo,redo,|,link,unlink,image,cleanup|preview,|,forecolor,backcolor",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	theme_advanced_statusbar_location : "bottom",
	theme_advanced_resizing : true,
	content_css : baseUrl+"/css/tinyMCE.css",
	theme_advanced_buttons3_add : "fullpage"

});
</script>
<fieldset class="form">
	<legend>CẬP NHẬT CHÂN TRANG</legend>
	<form id="form" method="post" action="">
	<table style="width:100%">
		<?php
		if(isset($this->success_msg)) {
		?>
		<tr>
			<td class="td_label"></td>
			<td>
				<div class="ui-state-highlight ui-corner-all" style=" padding: 0 .7em;">
					<p style="padding: 5px; color: green;"><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
					<strong>Success : </strong> <?php echo $this->success_msg?></p>
				</div>
			</td>
		</tr>
		<?php }?>
		<tr>
			<td class="td_label">Nội dung chân trang: </td>
			<td>
				<textarea style="width:600px" name="footer"><?php echo $this->footer?></textarea>
			</td>
		</tr>
		<tr>
			<td class="td_label"></td>
			<td>
				<input type="submit" id="btSubmit" value="Cập Nhật"/>
			</td>
		</tr>
	</table>
	</form>
</fieldset>
<script>
$(document).ready(function(){	
	$("#btSubmit").button();
});
</script>