<body>
<p>
<span style="font-size: 12px;"><span style="font-family: Tahoma,Geneva,sans-serif;">Xin ch&agrave;o <strong><?php echo $this->data['name']?></strong>,<br />
<br />
</span><span style="font-family: Arial,Helvetica,sans-serif;">Bạn hoặc một ai đ&oacute; vừa y&ecirc;u cầu cấp lại mật khẩu đăng nhập v&agrave;o hệ thống jobbid.vn.<br />
Nếu bạn muốn thay đổi mật khẩu đăng nhập, vui l&ograve;ng click v&agrave;o link b&ecirc;n dưới để nhập mật khẩu mới của bạn</span><br />
<br />
<a href="<?php echo $this->data['link_verify']?>"><?php echo $this->data['link_verify']?></a><br />
<br />
Xin cảm ơn bạn đ&atilde; sử dụng dịch vụ của jobbid.vn.<br />
Ban quản trị.<br />
<br />
<span style="color: rgb(128, 128, 128);">-----------------------------------------------------------------------------<br />
</span><a href="http://www.jobbid.vn/"><span style="color: rgb(128, 128, 128);">Jobbid.vn</span></a><span style="color: rgb(128, 128, 128);"> - Mạng x&atilde; hội việc l&agrave;m uy t&iacute;n tại Việt Nam.</span></span></span></p>
</body>