<body>
<p>
<span style="font-size: 12px;"><span style="font-family: Tahoma,Geneva,sans-serif;">Xin ch&agrave;o,<br />
<br />
Thay mặt ban quản trị trang web <strong>jobbid.vn</strong>, ch&uacute;ng t&ocirc;i xin th&ocirc;ng b&aacute;o th&ocirc;ng tin tuyển dụng của bạn đ&atilde; được ch&uacute;ng t&ocirc;i tổng hợp tự động v&agrave; đăng tải l&ecirc;n trang web jobbid.vn :</span></span><br />
<span style="font-size: 12px;"><span style="font-family: Tahoma,Geneva,sans-serif;"><span style="background-color: rgb(255, 215, 0);"><strong>Ti&ecirc;u đề</strong> : <?php echo $this->data['job_title']?></span></span></span><br />
<span style="font-family: Tahoma,Geneva,sans-serif;"><span style="font-size: 12px;"><span style="background-color: rgb(255, 215, 0);"><strong>M&ocirc; tả c&ocirc;ng việc</strong> : <?php echo $this->data['job_description']?></span></span></span></p>
<p>
<span style="font-family: Tahoma,Geneva,sans-serif;"><span style="font-size: 12px;">Link : <strong><a href="<?php echo $this->data['link_view']?>"><?php echo $this->data['link_view']?></a></strong></span><br />
<br />
<span style="font-size: 12px;">Nếu bạn kh&ocirc;ng đồng &yacute; đăng tin tuyển dụng n&agrave;y tại trang web của ch&uacute;ng t&ocirc;i, xin vui l&ograve;ng click v&agrave;o li&ecirc;n kết b&ecirc;n dưới để hủy đăng tin :</span><strong><a href="<?php echo $this->data['link_cancel']?>"><br />
<span style="color: rgb(255, 0, 0);"><span style="font-size: 12px;">Hủy tin đăng</span></span></a></strong></span></p>
<p>
<br />
<span style="font-size: 12px;"><span style="font-family: Tahoma,Geneva,sans-serif;">Xin cảm ơn bạn đ&atilde; sử dụng dịch vụ của <a href="http://www.jobbid.vn">jobbid.vn</a>.<br />
Ban quản trị.</span><br />
<br />
<span style="color: rgb(128, 128, 128);">-----------------------------------------------------------------------------<br />
</span><a href="http://www.jobbid.vn/"><span style="color: rgb(128, 128, 128);">Jobbid.vn</span></a><span style="color: rgb(128, 128, 128);"> - Mạng x&atilde; hội việc l&agrave;m uy t&iacute;n tại Việt Nam.</span></span><br />
<span style="color: rgb(128, 128, 128);"><span style="font-size: 11px;"><span style="font-family: Tahoma,Geneva,sans-serif;">Jobbid.vn l&agrave; s&agrave;n việc l&agrave;m để bạn c&oacute; thể đăng th&ocirc;ng tin tuyển dụng việc l&agrave;m th&ecirc;m, qua đ&oacute; t&igrave;m được ứng vi&ecirc;n th&iacute;ch hợp để thực hiện c&ocirc;ng việc của bạn. C&aacute;c bạn c&oacute; thể t&igrave;m kiếm được những c&ocirc;ng việc l&agrave;m th&ecirc;m hoặc c&aacute;c dự &aacute;n nhỏ ph&ugrave; hợp với khả năng của bạn.</span></span></span></p>
</body>