<body>
<p>
<span style="font-size: 12px;"><span style="font-family: Tahoma,Geneva,sans-serif;">Xin ch&agrave;o,<br />
<br />
Bạn (hoặc một ai đ&oacute;) đ&atilde; đăng th&ocirc;ng tin tuyển dụng tr&ecirc;n jobbid.vn :</span></span><br />
<span style="font-size: 12px;"><span style="font-family: Tahoma,Geneva,sans-serif;"><span style="background-color: rgb(255, 215, 0);"><strong>Ti&ecirc;u đề</strong> : <?php echo $this->data['job_title']?></span><br />
<span style="background-color: rgb(255, 215, 0);"><strong>M&ocirc; tả c&ocirc;ng việc</strong> : <?php echo $this->data['job_description']?></span><br />
<br />
Link : <a href="<?php echo $this->data['link_view']?>"><strong><?php echo $this->data['link_view']?></strong></a></span></span></p>
<p>
<span style="font-size: 12px;"><span style="font-family: Tahoma,Geneva,sans-serif;">Bạn vui l&ograve;ng v&agrave;o link b&ecirc;n dưới để x&aacute;c nhận tin đăng n&agrave;y (sau khi x&aacute;c nhận th&agrave;nh c&ocirc;ng th&igrave; tin đăng của bạn mới được hiển thị l&ecirc;n trang web jobbid.vn) :<br />
<br />
<a href="<?php echo $this->data['link_verify']?>">Link x&aacute;c nhận.</a><br />
<br />
Hoặc sử dụng m&atilde; x&aacute;c nhận sau : <span style="color: rgb(255, 0, 0);"><strong><?php echo $this->data['secure_key']?></strong></span><br />
<br />
Xin cảm ơn bạn đ&atilde; sử dụng dịch vụ của jobbid.vn.<br />
Ban quản trị.<br />
<br />
<span style="color: rgb(128, 128, 128);">-----------------------------------------------------------------------------<br />
</span><span style="font-size: 12px;"><a href="http://www.jobbid.vn/"><span style="color: rgb(128, 128, 128);">Jobbid.vn</span></a><span style="color: rgb(128, 128, 128);"> - Mạng x&atilde; hội việc l&agrave;m uy t&iacute;n tại Việt Nam.</span></span></span><br />
<span style="font-size: 12px;"> <span style="color: rgb(128, 128, 128);"><span style="font-family: Tahoma,Geneva,sans-serif;">Jobbid.vn l&agrave; s&agrave;n việc l&agrave;m để bạn c&oacute; thể đăng th&ocirc;ng tin tuyển dụng việc l&agrave;m th&ecirc;m, qua đ&oacute; t&igrave;m được ứng vi&ecirc;n th&iacute;ch hợp để thực hiện c&ocirc;ng việc của bạn. C&aacute;c bạn c&oacute; thể t&igrave;m kiếm được những c&ocirc;ng việc l&agrave;m th&ecirc;m hoặc c&aacute;c dự &aacute;n nhỏ ph&ugrave; hợp với khả năng của bạn.</span></span></span></span></p>
</body>