<body>
<p>
<span style="font-size: 12px;"><span style="font-family: Tahoma,Geneva,sans-serif;">Xin ch&agrave;o <?php echo $this->data['name']?>,<br />
<br />
Ch&uacute;c mừng bạn đ&atilde; đăng k&yacute; th&agrave;nh c&ocirc;ng t&agrave;i khoản tr&ecirc;n jobbid.vn.Bạn vui l&ograve;ng v&agrave;o link b&ecirc;n dưới để k&iacute;ch hoạt t&agrave;i khoản của bạn :<br />
<br />
<a href="<?php echo $this->data['link_verify']?>">Link x&aacute;c nhận.</a><br />
<br />
Hoặc sử dụng m&atilde; k&iacute;ch hoạt t&agrave;i khoản của bạn : <span style="color: rgb(255, 0, 0);"><strong><?php echo $this->data['secure_key']?></strong></span><br />
<br />
Xin cảm ơn bạn đ&atilde; sử dụng dịch vụ của jobbid.vn.<br />
Ban quản trị.<br />
<br />
<span style="color: rgb(128, 128, 128);">-----------------------------------------------------------------------------<br />
</span><a href="http://www.jobbid.vn/"><span style="color: rgb(128, 128, 128);">Jobbid.vn</span></a><span style="color: rgb(128, 128, 128);"> - Mạng x&atilde; hội việc l&agrave;m uy t&iacute;n tại Việt Nam.</span></span></span></p>
</body>