<body>
<p>
<span style="font-size: 12px;"><span style="font-family: Tahoma,Geneva,sans-serif;">Xin ch&agrave;o <?php echo $this->data['name']?>,<br />
<br />
Bạn (hoặc một ai đ&oacute;) đ&atilde; đăng th&ocirc;ng tin tuyển dụng cho vị tr&iacute; "<?php echo $this->data['job_title']?>" tr&ecirc;n jobbid.vn.Bạn vui l&ograve;ng v&agrave;o link b&ecirc;n dưới để x&aacute;c nhận tin đăng n&agrave;y (sau khi x&aacute;c nhận th&agrave;nh c&ocirc;ng th&igrave; tin đăng của bạn mới được hiển thị l&ecirc;n trang web jobbid.vn) :<br />
<br />
<a href="<?php echo $this->data['link_verify']?>">Link x&aacute;c nhận.</a><br />
<br />
Hoặc sử dụng m&atilde; x&aacute;c nhận sau : <span style="color: rgb(255, 0, 0);"><strong><?php echo $this->data['secure_key']?></strong></span><br />
<br />
Xin cảm ơn bạn đ&atilde; sử dụng dịch vụ của jobbid.vn.<br />
Ban quản trị.<br />
<br />
<span style="color: rgb(128, 128, 128);">-----------------------------------------------------------------------------<br />
</span><a href="http://www.jobbid.vn/"><span style="color: rgb(128, 128, 128);">Jobbid.vn</span></a><span style="color: rgb(128, 128, 128);"> - Mạng x&atilde; hội việc l&agrave;m uy t&iacute;n tại Việt Nam.</span></span></span></p>
</body>