<body>
<p>
	<span style="font-family: Tahoma,Geneva,sans-serif;">Ch&agrave;o bạn, jobbid.vn xin gửi bạn th&ocirc;ng tin c&ocirc;ng việc l&agrave;m th&ecirc;m b&ecirc;n dưới:</span></p>
<p>
	<span style="font-family: Tahoma,Geneva,sans-serif;"><span style="background-color: rgb(255, 215, 0);"><strong>C&ocirc;ng ty :</strong> <?php echo $this->data['company']?> </span><br />
	<span style="background-color: rgb(255, 215, 0);"><strong>Cần tuyển :</strong> <?php echo $this->data['job_title']?></span><br />
	<strong><span style="background-color: rgb(255, 215, 0);">M&ocirc; tả c&ocirc;ng việc :</span></strong><br />
	<span style="background-color: rgb(255, 215, 0);"><?php echo $this->data['job_description']?></span></span></p>
<p>
	<span style="font-family: Tahoma,Geneva,sans-serif;">Xem chi tiết : <strong><a href="<?php echo $this->data['link_view']?>"><?php echo $this->data['link_view']?></a></strong></span></p>
<p>
	<span style="color: rgb(128, 128, 128);">-----------------------------------------------------------------------------<br />
</span><span style="font-size: 12px;"><a href="http://www.jobbid.vn/"><span style="color: rgb(128, 128, 128);">Jobbid.vn</span></a><span style="color: rgb(128, 128, 128);"> - Mạng x&atilde; hội việc l&agrave;m uy t&iacute;n tại Việt Nam.</span></span></span><br />
<span style="font-size: 12px;"> <span style="color: rgb(128, 128, 128);"><span style="font-family: Tahoma,Geneva,sans-serif;">Jobbid.vn l&agrave; s&agrave;n việc l&agrave;m để bạn c&oacute; thể đăng th&ocirc;ng tin tuyển dụng việc l&agrave;m th&ecirc;m, qua đ&oacute; t&igrave;m được ứng vi&ecirc;n th&iacute;ch hợp để thực hiện c&ocirc;ng việc của bạn. C&aacute;c bạn c&oacute; thể t&igrave;m kiếm được những c&ocirc;ng việc l&agrave;m th&ecirc;m hoặc c&aacute;c dự &aacute;n nhỏ ph&ugrave; hợp với khả năng của bạn.</span></span></span></p>
</body>