<style>
.td_label {
width:100px
}
</style>
<div id="module_edit_message"></div>
<form id="module_edit_form" method="POST" >
<input type="text" style="display:none" id="ma_module" name="ma_module" value="">
<table style="width:100%">
	<tr>
		<td class="td_label">Tên module <span class="required">*</span> : </td>
		<td>
			<input type="text" class="field size2" id="ten_module" name="ten_module" value="">
			<label for="ten_module" generated="false" class="error"></label>
		</td>
	</tr>
	<tr>
		<td class="td_label">Vị trí <span class="required">*</span> : </td>
		<td>
			<select class="field" id="vitri" name="vitri">
				<option value="1">Bên trái</option>
				<option value="2">Ở giữa</option>
				<option value="3">Bên phải</option>
			</select>
		</td>
	</tr>
	<tr>
		<td class="td_label">Trạng thái <span class="required">*</span> : </td>
		<td>
			<select class="field" id="state" name="state">
				<option value="0">Ẩn</option>
				<option value="1">Hiển thị</option>
			</select>
		</td>
	</tr>
	<tr>
		<td class="td_label"></td>
		<td>
			<input id="btSave" type="button" value="Lưu"/>
			<input id="btClose" type="button" onclick="module_edit.doClose()" value="Thoát"/>
		</td>
	</tr>
</table>
</form>
<script>
var module_edit = {
	dialog : null,
	doClose : function() {
		module_edit.dialog.dialog("close");
	},
	init : function(){
		module_edit.dialog = $("#module_edit_form").parents(".ui-dialog-content");
		if(aDataSelected == '' || aDataSelected == null) {
			module_edit.dialog.dialog("close");
			return;
		};
		$.each(aDataSelected,function(key,value){
			$("#module_edit_form #"+key).val(value);
		});
		$("#module_edit_form #ten_module")[0].focus();
		$('#btClose').button().click(function(){
			module_edit.dialog.dialog("close");
		});
		$("#btSave").button().click(function(){
			//validate
			if($("#module_edit_form #ma_module").val() == '') return;
			if($("#module_edit_form #ten_module").val() == '') {
				alert("Vui lòng nhập tên module!");
				$("#module_edit_form #ten_module")[0].focus();
				return;
			}
			var dataString = $("#module_edit_form").serialize();
			var button = this;
			$(button).button({disabled: true});
			$.ajax({
				type: "POST",
				cache: false,
				url : baseUrl+'/admin/module/do-edit',
				data: dataString,
				success: function(response){
					$(button).button({disabled: null});
					if(response.rs == 'ERROR') {
						ajax_error(response.data);
					} else {
						module_edit.message("Cập nhật thành công!",1);
						reLoadData();
					}
				},
				error: function(data){$(button).button({disabled: null});}	
			});	
		});
	},
	message : function(msg,type) {
		if(msg == '') { // clear
			$("#module_edit_message",module_edit.dialog).empty();
			return;
		}
		if(type==1) { //Thong diep thong bao
			$("#module_edit_message",module_edit.dialog).html('<div class="ui-state-highlight ui-corner-all" style=" padding:5px"><p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span><strong>Success : </strong> '+msg+'</p></div>');
		} else if(type == 0) { //Thong diep bao loi
			$("#module_edit_message",module_edit.dialog).html('<div class="ui-state-error ui-corner-all" style="padding:5px"><p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span><strong>Error : </strong> '+msg+'</p></div>');
		}
	}
}
$(document).ready(function(){	
	module_edit.init();
});
</script>