<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/demo_table_jui.css" />
<fieldset class="form">
	<legend>QUẢN LÝ MODULE SẢN PHẨM</legend>
	<div style="float:right">
	<div class="admin_icon" title="Hiển thị" id="btShow">
		<img alt="Hiển thị" src="<?php echo $this->baseUrl()?>/icons/visible_32.png"/>
		<span>Hiển thị</span>
	</div>
	<div class="admin_icon" title="Ẩn" id="btHide">
		<img alt="Ẩn" src="<?php echo $this->baseUrl()?>/icons/invisible_32.png"/>
		<span>Ẩn</span>
	</div>
	</div>
</fieldset>
<div style="margin:10px">
<table width="100%" id="dataTable" class="display">
<thead>
	<tr>
		<th width="5%">#</th>
		<th>ma_module</th>
		<th>gianhang_id</th>
		<th>Tên module</th>
		<th>Vị trí</th>
		<th width="100px">Trạng thái</th>
		<th width="5px">Sửa</th>
		<th width="5px" align="center"><input type="checkbox" onclick="selectAll(this)"/></th>
	</tr>
</thead>
<tbody>
	<tr>
		<td colspan="10" class="dataTables_empty">Đang tải dữ liệu...</td>
	</tr>
</tbody>
</table>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/jquery.dataTables.min.js"></script>
<script>
function selectAll(_this) {
	$('#dataTable input[type=checkbox]').each(function(){
		this.checked=_this.checked;
	});
}
var pre_selected = null;
function doCheck(iDataIndex) {
	if(pre_selected!=null) {
		$(pre_selected).toggleClass('selected_row');
		pre_selected = null;
	}
	var tr = oTable.fnGetNodes(iDataIndex);
	$(tr).toggleClass('selected_row');
}
var aDataSelected = '';
function showEdit(iDataIndex){
	var tr = oTable.fnGetNodes(iDataIndex);
	aDataSelected = oTable.fnGetData(iDataIndex);
	if(aDataSelected == null) return;
	showDialogUrl(baseUrl + "/admin/module/edit","Cập nhật module",500);
}
function reLoadData(){
	oTable.fnDraw(false);
}
$(document).ready(function(){
	$(document).delegate("#btHide:not(.deactive)","click",function(){
		var button = $(this);
		var dataString = '';
		$("#dataTable tbody input[type=checkbox]:checked").each(function(){
			dataString+='&id[]='+this.value;
		});
		if(dataString == '') {
			alert('Bạn chưa chọn module cần ẩn!');
			return;
		}
		if(!confirm('Bạn muốn ẩn những module đã chọn?'))
			return;
		button.addClass("deactive").find('span').text("Đang xử lý...");
		$.ajax({
			type: "GET",
			cache: false,
			url : baseUrl+'/admin/module/update-state?state=0',
			data: dataString,
			success: function(data){
				button.removeClass("deactive").find('span').text("Ẩn");
				if(data.rs == 'ERROR') {
					ajax_error(data.data);
				} else {
					oTable.fnDraw(false);
				}
			},
			error: function(data){}	
		});	
	});
	$(document).delegate("#btShow:not(.deactive)","click",function(){
		var button = $(this);
		var dataString = '';
		$("#dataTable tbody input[type=checkbox]:checked").each(function(){
			dataString+='&id[]='+this.value;
		});
		if(dataString == '') {
			alert('Bạn chưa chọn module cần hiển thị!');
			return;
		}
		button.addClass("deactive").find('span').text("Đang xử lý...");
		$.ajax({
			type: "GET",
			cache: false,
			url : baseUrl+'/admin/module/update-state?state=1',
			data: dataString,
			success: function(data){
				button.removeClass("deactive").find('span').text("Hiển thị");
				if(data.rs == 'ERROR') {
					ajax_error(data.data);
				} else {
					oTable.fnDraw(false);
				}
			},
			error: function(data){}	
		});	
	});
	oTable = $('#dataTable').dataTable({
		'iDisplayLength': 100,
		"bJQueryUI": true,
		"bProcessing": true,
		"bScrollCollapse": true,
		"bServerSide": true,
		"bAutoWidth": false,
		"sAjaxSource": baseUrl+'/admin/module/list',
		"aoColumns": [
					{ "mDataProp": null,"bSortable": false,"fnRender" : function(oObj) { return oObj.iDataRow+1}},
					{ "mDataProp": "ma_module","bSortable": false,"sClass":"hidden"},
					{ "mDataProp": "gianhang_id","bSortable": false,"sClass":"hidden"},
					{ "mDataProp": "ten_module","bSortable": false},
					{ 	"mDataProp": null,"bSortable": false,"sClass": "td_center",
						"fnRender": function( oObj ) {
							if(oObj.aData.vitri == '1') {
								return 'Bên trái';
							} else if(oObj.aData.vitri == '2') {
								return 'Ở giữa';
							} else {
								return "Bên phải";
							}
						}
					},
					{ 	"mDataProp": null,"bSortable": false,"sClass": "td_center",
						"fnRender": function( oObj ) {
							if(oObj.aData.state == '1') {
								return 'Hiển thị';
							} else if(oObj.aData.state == '0') {
								return 'Ẩn';
							}
						}
					},
					{ 	"mDataProp": null,"bSortable": false,
						"fnRender": function( oObj ) {
							return '<center><img title="Edit" src="'+baseUrl+'/images/icons/edit.png" style="cursor:pointer" onclick="showEdit('+oObj.iDataRow+')"/></center>'; 
						}
					},
					{ 	"mDataProp": null,"bSortable": false,
						"fnRender": function( oObj ) {
							return '<center><input type="checkbox" onclick="doCheck('+oObj.iDataRow+')" value="'+oObj.aData.ma_module+'"/></center>'; 
						}
					}
				],
		"fnServerData": function ( sSource, aoData, fnCallback ) {
			$.ajax( {
				"dataType": 'json', 
				"type": "POST", 
				"url": sSource, 
				"data": aoData, 
				"success": function(data){
					if(data.rs == 'ERROR') {
						ajax_error(data.data);
					} else {
						fnCallback(data);
					}
				}
			} );
		},
		"sPaginationType": "two_button"
	});
});
</script>