<?php
$baseUrl = $this->baseUrl();
$actual_link = Core_Utils_Tools::getFullURL();
?>
<link rel="stylesheet" href="<?php echo $baseUrl?>/css/post.css" type="text/css" media="screen" />
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.validate.js"></script>
<script type='text/javascript' src='<?php echo $baseUrl?>/js/jquery-ui/jquery.ui.autocomplete.min.js'></script>
<!--[if lt IE 8]><style>
.wraptocenter span {
    display: inline-block;
    height: 100%;
}
</style><![endif]-->
<div id="fb-root"></div>
<!--div id="left_col">
	<a class="logo" style="text-decoration: none; text-align: center;" href="<?php echo $baseUrl ?>"/><img style="border: medium none; " src="<?php echo $baseUrl ?>/images/logo.png" alt="logo"/>
				<span class="slogan">Mạng xã hội việc làm Việt Nam</span></a>
</div-->
<div id="right_col" style="margin-left:10px">
	<div style="width: 500px; margin: 0px auto 0px; text-align: left;float:left">
	<h1 style="text-align: left; border-bottom: 1px dashed gray; padding-bottom: 10px; margin-bottom: 10px;">Đăng ký tài khoản jobbid.vn</h1>
	<?php echo $this->form?>
	</div>
</div>
<script type='text/javascript'>
$(document).ready(function(){	
	var isPopup = '<?php echo $this->isPopup?>';
	if(isPopup == '1') {
		$("#fRegistration #isPopup").val(isPopup);
	}
	<?php
	foreach($this->errors as $key => $error) {
		$msg = join(',', $error);
		?>
		$("#fRegistration label[for=<?php echo $key?>]").text("<?php echo $msg?>");
		$("#fRegistration #<?php echo $key?>").css("border","1px solid red");
		<?php
	}
	?>
});
</script>