<?php
$baseUrl = $this->baseUrl();
$actual_link = Core_Utils_Tools::getFullURL();
?>
<!--[if lt IE 8]><style>
.wraptocenter span {
    display: inline-block;
    height: 100%;
}
</style><![endif]-->
<link rel="stylesheet" href="<?php echo $baseUrl?>/css/post.css" type="text/css" media="screen" />
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.validate.js"></script>
<div id="right_col" style="margin-left:10px">
	<div style="width: 500px; margin: 20px auto 0px; text-align: left; float: left;">
	<h1 style="text-align: left; border-bottom: 1px dashed gray; padding-bottom: 10px; margin-bottom: 10px;">Xác thực tài khoản</h1>
	<span style="font-size: 12px; color: gray;">Mã xác thực đã được gửi vào email <b><?php echo $this->email?></b>,vui lòng kiểm tra email <b><?php echo $this->email?></b> và nhập mã xác thực vào ô bên dưới để kích hoạt tài khoản của bạn.</span>
	<form id="fVerify" action="" method="post" onsubmit="return false;">
	<table	style="width:100%">
	<tr>
		<td style="width:120px">Nhập mã xác thực :</td>
		<td>
		<input type="text" name="verify_key" value="<?php echo $this->secure_key?>" class="text element" id="verify_key"/> <span class="warning" title="Mã xác thực được gửi vào địa chỉ email mà bạn đã đăng ký tại jobbid.vn">*</span>
		<label for="verify_key" generated="false" class="error"></label>
		</td>
	</tr>
	<tr>
		<td></td>
		<td>
			<button id="btSubmit" class="button element">Xác nhận</button>
		</tr>
	</table>
	</form>
</div>
	</div>
</div>
<script type='text/javascript'>
var isPopup = '<?php echo $this->is_popup?>'; 
$(document).ready(function(){	
	$("#verify_key").focus();
	$("#fVerify").validate({
	  rules: {
		verify_key: {
			required: true
		}
	  }
	});
	$("#fVerify").live("submit",function(){
		var form = $(this);
		form.find('.element').attr('disabled', 'disabled');
		$.ajax({
			type : "POST",
			cache: false,
			url: baseUrl +'/ajax/verify-registration',
			data : {key : $("#verify_key").val()},
			success : function(data){	
				form.find('.element').removeAttr('disabled');
				if(data=='ERROR') {
					alert(ERROR_MESSAGE);
					return;
				}
				if(data=='LIMIT') {
					alert(LIMIT_VERIFY_FAILED);
					form.find('.element').attr('disabled', 'disabled');
					return;
				}
				if(data=='FAILED') {
					alert('Mã xác nhận không đúng, vui lòng thử lại!');
					return;
				}
				if(isPopup == '1') {
					if(typeof window.opener.loginSucces == 'function') {
						window.opener.loginSuccess();
					} else {
						window.opener.location.reload();
					}
					window.close();
				} else {
					location.href = data;
				}
			},
			error: function(data){ 
				alert(ERROR_MESSAGE);
				form.find('.element').removeAttr('disabled');
			}			
		});
		return false;
	});
});
</script>