<?php
$baseUrl = $this->baseUrl();
?>
<link rel="stylesheet" href="<?php echo $baseUrl?>/css/post.css" type="text/css" media="screen" />
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.validate.js"></script>

<div id="right_col">
	<?php
	if(!empty($this->result_msg['error'])) {
	?>
		<div class="ui-state-error ui-corner-all" style="padding: 0px 0.7em; margin-top: 10px;">
			<p style="padding: 3px; text-align: left; margin: 0px;"><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
			<strong>Lỗi : </strong> <?php echo $this->result_msg['error']?></p>
		</div>
	<?php
	} else if(!empty($this->result_msg['success'])) {
	?>
	<div class="ui-state-highlight ui-corner-all" style=" padding: 0px 0.7em; margin-top: 10px;">
		<p style="padding: 3px; text-align: left; margin: 0px;"><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
		<strong>Bước 2 : </strong> Vui lòng kiểm tra email "<?php echo $this->result_msg['success']?>" để lấy link đổi mật khẩu</p>
	</div>
	<?php
	}
	?>
	<span style="text-align: left; display: block; margin-top: 5px; ">Vui lòng điền email đăng nhập của bạn.</span>
	<form id="fForgotPassword" action="" method="post" >
	<table	style="width:100%;margin-top:10px">
	<tr>
		<td>
		<input type="text" name="username" value="<?php echo $this->secure_key?>" class="text element" id="username"/>
		<label for="username" generated="false" class="error"></label>
		</td>
	</tr>
	<tr>
		<td>
			<button id="btSubmit" class="button element">Gửi đi</button>
		</tr>
	</table>
	</form>
</div>
<script type='text/javascript'>
$(document).ready(function(){	
	$("#username").focus();
	$("#fForgotPassword").validate({
	  rules: {
		username: {
			required: true
		}
	  }
	});
});
</script>