<?php
$baseUrl = $this->baseUrl();

?>
<!--[if lt IE 8]><style>
.wraptocenter span {
    display: inline-block;
    height: 100%;
}
</style><![endif]-->
<div id="right_col" style="margin-left:10px">
	<div style="width: 500px; margin: 20px auto 0px; text-align: left; float: left;">
		Bạn đã đăng nhập thành công với tài khoản ...
	</div>
</div>
<script type='text/javascript'>
function redirect(){
	location.href = redirect_url;
}
var redirect_url = '<?php echo $this->redirect_url?>';
$(document).ready(function(){	
	if(typeof window.parent.loginSuccess == 'function') {
		window.parent.loginSuccess();
	} else {
		window.parent.location.reload();
	}
});
</script>