<?php
$baseUrl = $this->baseUrl();

?>
<!--[if lt IE 8]><style>
.wraptocenter span {
    display: inline-block;
    height: 100%;
}
</style><![endif]-->
<div id="right_col" style="margin-left:10px">
	<div style="width: 500px; margin: 20px auto 0px; text-align: left; float: left;">
		Bạn đã đăng nhập thành công với tài khoản ...
	</div>
</div>
<script type='text/javascript'>
function redirect(){
	location.href = redirect_url;
}
var redirect_url = '<?php echo $this->redirect_url?>';
$(document).ready(function(){	
	var isPopup = '<?php echo $this->isPopup?>';
	if(isPopup == '1') {
		if(typeof window.opener.loginSucces == 'function') {
			window.opener.loginSuccess();
		} else {
			window.opener.location.reload();
		}
		window.close();
	} else {
		setTimeout("redirect()",3);
	}
});
</script>