<?php
$baseUrl = $this->baseUrl();
?>
<link rel="stylesheet" href="<?php echo $baseUrl?>/css/post.css" type="text/css" media="screen" />
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.validate.js"></script>

<div id="right_col">
	<?php
	if(!empty($this->result_msg['error'])) {
	?>
		<div class="ui-state-error ui-corner-all" style="padding: 0px 0.7em; margin-top: 10px;">
			<p style="padding: 3px; text-align: left; margin: 0px;"><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
			<strong>Lỗi : </strong> <?php echo $this->result_msg['error']?></p>
		</div>
	<?php
	} else if(!empty($this->result_msg['success'])) {
	?>
	<div class="ui-state-highlight ui-corner-all" style=" padding: 0px 0.7em; margin-top: 10px;">
		<p style="padding: 3px; text-align: left; margin: 0px;"><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
		<strong>Thay đổi mật khẩu đăng nhập thành công!</strong> Vui lòng <a href="<?php echo $baseUrl?>/user/login?is_popup=1" title="Đăng nhập" class="popup login">đăng nhập</a> vào hệ thống bằng mật khẩu mới</p>
	</div>
	<?php
	}
	?>
	<span style="text-align: left; display: block; margin-top: 5px; ">Vui lòng nhập mật khẩu đăng nhập mới của bạn vào ô bên dưới :</span>
	<form id="fForgotPassword" action="" method="post" >
	<input type="hidden" name="secure_key" value="<?php echo $this->secure_key?>"/>
	<table	style="width:100%;margin-top:10px">
	<tr>
		<td>
		<input type="password" name="password" value="" class="text element" id="password"/>
		<label for="password" generated="false" class="error"></label>
		</td>
	</tr>
	<tr>
		<td>
			<button id="btSubmit" class="button element">Xác nhận</button>
		</tr>
	</table>
	</form>
</div>
<script type='text/javascript'>
$(document).ready(function(){	
	$("#password").focus();
	$("#fForgotPassword").validate({
	  rules: {
		password: {
			required: true
		}
	  }
	});
});
</script>