<?php
$baseUrl = $this->baseUrl();
?>
<div style="text-align:left">
<form method="post" action="" >
<input type="text" id="zingid" name="zingid" placeholder="zingid" value="<?php echo $this->zingid?>" style="display: block; margin-top: 5px; width: 200px;"/>
<input type="text" id="num" name="num" placeholder="Num" value="" style="display: block; margin-top: 5px; width: 80px;"/>
<div style="margin-top:5px">
<input type="submit" value="Test"/>
</form>
</div>
</div>
<div style="text-align:left">
<?php echo $this->content?>
</div>
<script>
var delay = 200;
var maxloop = 50;
var baseUrl = '<?php echo $baseUrl?>/shop/';
var cookie = '';
var i = 1;
var isRun = false;
function Countdown(options){var timer,instance=this,seconds=options.seconds||10,updateStatus=options.onUpdateStatus||function(){},counterEnd=options.onCounterEnd||function(){};function decrementCounter(){updateStatus(seconds);if(seconds===0){counterEnd();instance.stop();}
seconds--;}
this.start=function(){clearInterval(timer);timer=0;seconds=options.seconds;timer=setInterval(decrementCounter,1000);};this.stop=function(){clearInterval(timer);};}
function stop() {
	isRun = false;
}
function start() {
	isRun = true;
	cookie = $("#cookie").val();
	delay = $("#delay").val();
	maxloop = $("#maxloop").val();
	hack();
}
function getContent() {
	cookie = $("#cookie").val();
	var url = $("#url").val();
	$.ajax({  
		type: 'POST',
		cache: false,
		data: {
			'cookie' : cookie,
			'url' : url
		},
		url: baseUrl + 'get-content',
		success: function(data){
			console.log('OK');
		},
		error: function(){
			console.log('ERROR');
		}
	}); 
}
function run() {
	$.ajax({  
		type: 'POST',
		cache: false,
		data: {
			'zingid' : $("#zingid").val()
		},
		url: baseUrl + 'test',
		success: function(data){
			console.log(data);
		},
		error: function(){
			console.log('ERROR');
		}
	}); 
}
function hack() {
	if(isRun == false) return;
	if(maxloop <= 0) return;
	run();
	setTimeout("hack()",delay);
	maxloop--;
	$("#maxloop").val(maxloop);
}
function refesh() {
	$.ajax({  
		type: 'GET',
		cache: false,
		url: document.location,
		success: function(data){
			c.seconds = data.count;
		},
		error: function(){
			console.log('ERROR');
		}
	}); 
	setTimeout("refesh()",60000);
}
var c;
$(document).ready(function(){
	
});
</script>