<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if IE 6]>
<html class="ie" id="ie6">
<![endif]-->
<!--[if IE 7]>
<html class="ie" id="ie7">
<![endif]-->
<!--[if IE 8]>
<html class="ie" id="ie8">
<![endif]-->
<!--[if IE 9]>
<html class="ie" id="ie9">
<![endif]-->
<!--[if !(IE 6) | !(IE 7) | !(IE 8)  ]><!-->
<html>
<!--<![endif]-->
<head>
<?php
$session = new Zend_Session_Namespace('session');
$actual_link = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
$baseUrl = $this->baseUrl();
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="<?php echo $baseUrl?>/favico.ico">
<title><?php echo isset($this->title)?$this->title:SITE_TITLE ?></title>
<meta http-equiv="content-language" content="vi"/>
<meta content="Vietnamese, Vietnam" name="language">
<meta name="robots" content="index, follow"/>
<meta content="<?php echo isset($this->description)?$this->description:SITE_DESCRIPTION ?>" name="description"/>
<meta content="<?php echo isset($this->keywords)?$this->keywords:SITE_KEYWORDS ?>" name="keywords"/>
<meta content="jobbid.vn" name="author"/>
<meta content="jobbid.vn" name="copyright"/>
<link rel="stylesheet" href="<?php echo $baseUrl?>/css/front_style.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $baseUrl?>/css/jquery-ui.css" type="text/css" media="screen" />
<!--Internet Explorer Trancparency fix-->
<!--[if IE 6]>
<script src="/<?php echo $baseUrl?>/js/ie6pngfix.js"></script>
<script>
  DD_belatedPNG.fix('#head, a, a span, img, .message p, .click_to_close, .ie6fix');
</script>
<![endif]--> 

<script type='text/javascript' src='<?php echo $baseUrl?>/js/jquery.js'></script>
<script type='text/javascript' src='<?php echo $baseUrl?>/js/jquery-ui.min.js'></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.placeholder.min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.timeago.js"></script>
<script src="<?php echo $baseUrl?>/js/jquery-window/jquery.window.min.js" type="text/javascript"></script>
<link href="<?php echo $baseUrl?>/js/jquery-window/css/jquery.window.css" type="text/css" rel="stylesheet">
<script type="text/javascript" src="<?php echo $baseUrl?>/js/mylibs/utils.js"></script>
<script>
var baseUrl = '<?php echo $baseUrl?>';
function byId(id) { //Viet tat cua ham document.getElementById
	return document.getElementById(id);
}
function ajdebug(val) {
	alert(val);
}
</script>
</head>
<body class="gradients">
	<div id="page">
		<div id="header">
			<center>
			<div style="width: 978px; height: 30px; position: relative;">
				<div id="menu_bar"> 
					<a href="<?php echo $baseUrl?>/" title="Trang chủ">Trang chủ</a>
					<a href="<?php echo $baseUrl?>/job/create-job" title="Dành cho nhà tuyển dụng : đăng thông tin cần tuyển dụng nhân sự trên jobbid.vn" style="color: red;">Đăng tuyển dụng</a>
					<a href="<?php echo $baseUrl?>/tintuc" title="Tin tức làm thêm">Tin tức</a>
					<a href="<?php echo $baseUrl?>/raovat" title="Rao vặt làm thêm">Rao vặt</a>
				</div>
				<div id="account_bar"> 
					<?php
					$logged_info = $session->logged;
					if(isset($logged_info)) {
					?>
					<a>Xin chào <?php echo $logged_info['name']?></a>
					<?php 
					if($logged_info['active'] == 0) {
						?>
						<a href="<?php echo $baseUrl?>/registration/verify?is_popup=1" title="Kích hoạt tài khoản" class="popup verify" style="color:red">Chưa kích hoạt</a>
						<?php
					}
					?>
					<a href="<?php echo $baseUrl?>/job/my-jobs" class="popup" title="Quản lý công việc bạn đã đăng lên jobbid.vn">Your jobs</a>
					<a href="<?php echo $baseUrl?>/user/update?is_popup=1" title="Cập nhật Thông tin cá nhân" class="popup">Thông tin cá nhân</a>
					<a href="<?php echo $baseUrl?>/user/logout" title="Đăng xuất">Logout</a>
					<?php
					} else {
					?>
					<a href="<?php echo $baseUrl?>/user/login?is_popup=1" title="Đăng nhập" style="padding-right:20px" class="popup login">Đăng nhập</a>
					<a href="<?php echo $baseUrl?>/registration/jobbid?is_popup=1" title="Đăng ký" class="popup registration">Đăng ký</a>
					<?php
					}
					?>
				</div>
			</div>
			</center>
		</div>
		<center>
		<div id="main">
		<?php echo $this->layout()->content;?>
		</div>
		</center>
		<div id="footer">
			<center>
			<div style="width: 978px; height: 120px; position: relative;">
				<div class="address">
				<p style="padding-top:15px"> 
					MẠNG XÃ HỘI VIỆC LÀM VIỆT NAM<br/>
					Điện thoại : 0932 337 487 - Email : <a href="mailto:lienhe@jobbid.vn">lienhe@jobbid.vn</a>
				</p>
				</div>
			</div>
			</center>
		</div>
	</div>
</body>
</html>
<script type="text/javascript">
var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21846705-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  
var ERROR_MESSAGE = 'Có lỗi xảy ra, vui lòng thử lại.';
var PROCESSING_MESSAGE = 'Đang xử lý...';
var LIMIT_VERIFY_FAILED = 'Bạn đã xác thực sai quá <?php echo LIMIT_VERIFY_FAILED?> lần.\nVui lòng xác thực lại sau 15 phút.';
$(document).ready(function(){	 
	$("a.popup").live("click",function(event){
		event.stopPropagation();
		event.preventDefault();
		ShowWindow(this.href,$(this).text(),500,350);
		return false;
	});
	/*if($("#page #content").height()+218 < $(window).height()) {
		$("#bottom").attr('style','position:fixed;bottom:0');
	}*/
});
</script>