<!--[if IE 6]>
<html class="ie" id="ie6">
<![endif]-->
<!--[if IE 7]>
<html class="ie" id="ie7">
<![endif]-->
<!--[if IE 8]>
<html class="ie" id="ie8">
<![endif]-->
<!--[if IE 9]>
<html class="ie" id="ie9">
<![endif]-->
<!--[if !(IE 6) | !(IE 7) | !(IE 8)  ]><!-->
<html>
<!--<![endif]-->
<head>
<?php
$actual_link = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
$baseUrl = $this->baseUrl();
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="<?php echo $baseUrl?>/favico.ico">
<title><?php echo (isset($this->title)?$this->title.' - ':'').SITE_TITLE ?></title>
<link rel="stylesheet" href="<?php echo $baseUrl?>/css/front_style.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $baseUrl?>/css/jquery-ui.css" type="text/css" media="screen" />
<!--Internet Explorer Trancparency fix-->
<!--[if IE 6]>
<script src="/<?php echo $baseUrl?>/js/ie6pngfix.js"></script>
<script>
  DD_belatedPNG.fix('#head, a, a span, img, .message p, .click_to_close, .ie6fix');
</script>
<![endif]--> 

<script type='text/javascript' src='<?php echo $baseUrl?>/js/jquery.js'></script>
<script type='text/javascript' src='<?php echo $baseUrl?>/js/jquery-ui/jquery.ui.core.min.js'></script>
<script type='text/javascript' src='<?php echo $baseUrl?>/js/jquery-ui/jquery.ui.widget.min.js'></script>
<script type='text/javascript' src='<?php echo $baseUrl?>/js/jquery-ui/jquery.ui.button.min.js'></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/mylibs/utils.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.placeholder.min.js"></script>
<script>
var baseUrl = '<?php echo $baseUrl?>';
function byId(id) { //Viet tat cua ham document.getElementById
	return document.getElementById(id);
}
function ajdebug(val) {
	alert(val);
}
</script>
</head>
<body class="gradients">
	<div id="page">
		<div id="header">
			<center>
			<div style="width: 978px; height: 30px; position: relative;">
				<div id="menu_bar"> 
					<a href="#" title="">Trang chủ</a>
					<a href="#" title="">Tìm việc</a>
					<a href="#" title="">Tìm ứng viên</a>
					<a href="#" title="">Liên hệ</a>
				</div>
			</div>
			</center>
		</div>
		<center>
		<div id="main">
		<?php echo $this->layout()->content;?>
		</div>
		</center>
		<div id="footer">
			<center>
			<div style="width: 978px; height: 120px; position: relative;">
				<div class="address">
				<p style="padding-top:15px"> 
					MẠNG XÃ HỘI VIỆC LÀM VIỆT NAM<br/>
					Điện thoại : 0932 337 487 - Email : <a href="mailto:lienhe@jobbid.vn">lienhe@jobbid.vn</a>
				</p>
				</div>
			</div>
			</center>
		</div>
	</div>
</body>
</html>
<script>
var ERROR_MESSAGE = 'Có lỗi xảy ra, vui lòng thử lại.';
var PROCESSING_MESSAGE = 'Đang xử lý...';
$(document).ready(function(){	 
	
	/*if($("#page #content").height()+218 < $(window).height()) {
		$("#bottom").attr('style','position:fixed;bottom:0');
	}*/
});
</script>