<!doctype html>
<html>
<head><meta charset="utf-8"></head>
<body>
<header><h1>Google UserInfo Sample App</h1></header>
<?php if(isset($this->personMarkup)): ?>
<?php print $this->personMarkup ?>
<?php endif ?>
<?php
  if(isset($this->authUrl)) {
    print "<a class='login' href='$this->authUrl'>Connect Me!</a>";
  } else {
   print "<a class='logout' href='?logout'>Logout</a>";
  }
?>
</body></html>