<?php
$baseUrl = $this->baseUrl();
?>
<!--[if lt IE 8]><style>
.wraptocenter span {
    display: inline-block;
    height: 100%;
}
</style><![endif]-->
<?php echo $this->render('/templates/left.phtml')?>
<div id="right_col">
	<h1 style="text-align: left; border-bottom: 1px dashed gray; margin-bottom: 5px; padding-bottom: 10px;">Tags cloud</h1>
	<?php echo $this->cloud ?>
</div>
</div>
<script>
$(document).ready(function(){
	
});
</script>