<?php
$baseUrl = $this->baseUrl();
?>
<link rel="stylesheet" href="<?php echo $baseUrl?>/css/post.css" type="text/css" media="screen" />
<script type="text/javascript" src="<?php echo $baseUrl?>/js/jquery.validate.js"></script>
<script type='text/javascript' src='<?php echo $baseUrl?>/js/jquery-ui/jquery.ui.autocomplete.min.js'></script>
<!--[if lt IE 8]><style>
.wraptocenter span {
    display: inline-block;
    height: 100%;
}
</style><![endif]-->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/all.js#xfbml=1&appId=344438602327914";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="left_col">
	<!--a class="logo" style="text-decoration: none; text-align: center;" href="<?php echo $baseUrl ?>"/><img style="border: medium none; " src="<?php echo $baseUrl ?>/images/logo.png" alt="logo"/>
				<span class="slogan">Mạng xã hội việc làm Việt Nam</span></a-->
</div>
<div id="right_col">
	<center>
	<div style="width: 600px; margin: 20px auto 0px; text-align: left;">
	<span style="color: gray; font-size: 11px; text-align: right; width: 100%; display: block;">22/02/2013 16:45</span>
	<h1>Vina Design - Tuyển Nhân Viên Thiết Kế Đồ Họa Photoshop, Flash</h1>
	<table style="width:100%">
		<tr>
			<td style="width:100px"><span class="bold">Công ty :</span></td>
			<td>
				<a href="#" title="">Lạc Việt</a>
			</td>
		</tr>
		<tr>
			<td><span class="bold">Cần tuyển :</span></td>
			<td>
				<a href="#" title="">Chuyên viên SEO</a>
			</td>
		</tr>
		<tr>
			<td><span class="bold">Làm việc tại :</span></td>
			<td>
				<a href="#" title="">TP Hồ Chí Minh</a>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<span class="bold">Mô tả công việc :</span><br/>
				<pre>
- Công việc đòi hỏi tính sáng tạo cao, có nhiều ý tưởng mới,hay và đặc biệt.
- Có kỹ năng và thẩm mỹ trong thiết kế website, brochures, posters, etc.
- có khả năng sử dụng thành thạo các công cụ thiết kế (như vẽ tay và các phần mềm thiết kế đồ họa) để đưa những ý tưởng sáng tạo vào ứng dụng thực tiễn.
- Làm việc trong môi trường có tính sáng tạo cao
- Nội dung công việc, thời gian làm việc và các vấn đề chi tiết sẽ trao đổi trong vòng phỏng vấn</pre>
			</td>
		</tr>
		<tr>
			<td><span class="bold">Loại công việc :</span></td>
			<td>
				Part-time
			</td>
		</tr>
		<tr>
			<td><span class="bold">Email liên hệ :</span></td>
			<td>
				<a href="#" title="">sieumuachung@yahoo.com</a>
			</td>
		</tr>
		<tr>
			<td colspan="2" align="right">
				<span class="jb_button share" title="Chia sẽ lên Facebook">Share</span>
				<span class="jb_button report" title="Báo cáo tin đăng xấu">Unlike</span>
			</td>
		</tr>
	</table>
	<fieldset style="margin-top:20px">
		<legend>Những công việc tương tự</legend>
		<a href="#" style="display:block">- Vina Design - Tuyển Marketing Online Executive</a>
		<a href="#" style="display:block">- Vina Design - Tuyển Marketing Online Executive</a>
		<a href="#" style="display:block">- Vina Design - Tuyển Marketing Online Executive</a>
		<a href="#" style="display:block">- Vina Design - Tuyển Marketing Online Executive</a>
		<a href="#" style="display:block">- Vina Design - Tuyển Marketing Online Executive</a>
	</fieldset>
	<div class="fb-comments" data-href="http://www.jobbid.vn/raovat/view/4461/magicwall-tu-van-cho-ban-trang-tri-to-am" data-width="600" data-num-posts="10"></div>
	</div>
	</center>
	
</div>
<script type='text/javascript'>
//<![CDATA[
String.prototype.GetValue= function(para) {
var reg = new RegExp("(^|&)"+ para +"=([^&]*)(&|$)");
var r = this.substr(this.indexOf("\?")+1).match(reg);
if (r!=null) return unescape(r[2]); return null;
}
var purl= location.href;
var cm_form = purl.GetValue("cm_form");
var fb_href = purl;
var fbcm ='<div class="fb-comments" data-href="'+fb_href+'" data-num-posts="5" data-width="660"></div>';
//]]>
$(document).ready(function(){	
	$("span.fb_sharebutton").live("click",function(){
		window.open("http://www.facebook.com/share.php?u=http%3A%2F%2Fwww.jobbid.vn%2Fraovat%2Fview%2F4461%2Fmagicwall-tu-van-cho-ban-trang-tri-to-am", "window_name","location=1,status=1,scrollbars=1,resizable=no,width=500,height=400");
	});
});
</script>