<?php
$baseUrl = $this->baseUrl();
?>
<!--[if lt IE 8]><style>
.wraptocenter span {
    display: inline-block;
    height: 100%;
}
</style><![endif]-->
<?php echo $this->render('/templates/left.phtml')?>
<div id="right_col">
	<div id="search">
		<?php echo $this->form?>
	</div>
	<?php
	foreach($this->jobs as $job) {
		echo $this->partial('/templates/list.phtml',array('job'=>$job,'baseUrl' => $baseUrl));
	}
	?>
</div>
</div>
<script>
$(document).ready(function(){
	$("abbr.timeago").timeago();
	$('input[placeholder], textarea[placeholder]').placeholder();
	$("div.row").live("hover",function(event){
		if( event.type === 'mouseenter' ) {
			$(this).css("background-color","lightyellow");
		} else {
			$(this).css("background-color","");
		}
	});
});
</script>