<?php
$baseUrl = $this->baseUrl();
?>
<span id="count_down"></span>
<script>
var delay = 200;
var maxloop = 5;
var baseUrl = '<?php echo $baseUrl?>';
var count = <?php echo $this->count?>;
var cookie = '';
var i = 1;
function Countdown(options){var timer,instance=this,seconds=options.seconds||10,updateStatus=options.onUpdateStatus||function(){},counterEnd=options.onCounterEnd||function(){};function decrementCounter(){updateStatus(seconds);if(seconds===0){counterEnd();instance.stop();}
seconds--;}
this.start=function(){clearInterval(timer);timer=0;seconds=options.seconds;timer=setInterval(decrementCounter,1000);};this.stop=function(){clearInterval(timer);};}
function hack() {
	if(i>maxloop) return;
	$.ajax({  
		type: 'POST',
		cache: false,
		data: {
			'cookie' : cookie
		},
		url: baseUrl + '/test/promotion',
		success: function(data){
			console.log('OK');
		},
		error: function(){
			console.log('ERROR');
		}
	}); 
	setTimeout("hack()",delay);
	i++;
}
$(document).ready(function(){
	var c = new Countdown({
		'seconds' : count,
		'onUpdateStatus' : function(seconds) {
			var hour = 0;
			var minute = 0;

			if(seconds >= 3600) {
				hour = Math.floor(seconds / 3600);
			}
			if(seconds >= 60) {
				minute = Math.floor((seconds - hour * 3600) / 60);
			}
			var second = seconds - hour * 3600 - minute * 60;
			$("#count_down").text(hour + ":" + minute + ":" + second);
		},
		'onCounterEnd' : function() {
			hack();
		}
	});
	c.start();
});
</script>