<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/demo_table_jui.css" />
<script src="<?php echo $this->baseUrl()?>/js/jquery.jeditable.mini.js" type="text/javascript" ></script>
<fieldset class="form">
	<legend>QUẢN LÝ SLIDE HÌNH ẢNH</legend>
	<div style="float:right">
	<div class="admin_icon" title="Thêm mới" onclick='location.href = "<?php echo $this->baseUrl()?>/admin/slide/add"'>
		<img alt="Thêm mới" src="<?php echo $this->baseUrl()?>/icons/add_32.png"/>
		<span>Thêm Mới</span>
	</div>
	<div class="admin_icon" title="Hiển thị" id="btShow">
		<img alt="Hiển thị" src="<?php echo $this->baseUrl()?>/icons/visible_32.png"/>
		<span>Hiển thị</span>
	</div>
	<div class="admin_icon" title="Ẩn" id="btHide">
		<img alt="Ẩn" src="<?php echo $this->baseUrl()?>/icons/invisible_32.png"/>
		<span>Ẩn</span>
	</div>
	<div class="admin_icon" title="Xóa" id="btXoa">
		<img alt="Xóa" src="<?php echo $this->baseUrl()?>/icons/delete_32.png"/>
		<span>Xóa</span>
	</div>
	</div>
</fieldset>
<div style="margin:10px">
<table width="100%" id="dataTable" class="display">
<thead>
	<tr>
		<th width="5%">#</th>
		<th>id</th>
		<th>Hình ảnh</th>
		<th width="50px">Vị trí</th>
		<th width="100px">Trạng thái</th>
		<th width="5px" align="center"><input type="checkbox" onclick="selectAll(this)"/></th>
	</tr>
</thead>
<tbody>
	<tr>
		<td colspan="8" class="dataTables_empty">Đang tải dữ liệu...</td>
	</tr>
</tbody>
</table>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/jquery.dataTables.min.js"></script>
<script>
function selectAll(_this) {
	$('#dataTable input[type=checkbox]').each(function(){
		this.checked=_this.checked;
	});
}
var pre_selected = null;
function doCheck(iDataIndex) {
	if(pre_selected!=null) {
		$(pre_selected).toggleClass('selected_row');
		pre_selected = null;
	}
	var tr = oTable.fnGetNodes(iDataIndex);
	$(tr).toggleClass('selected_row');
}
var aDataSelected = '';
function showEdit(iDataIndex){
	var tr = oTable.fnGetNodes(iDataIndex);
	aDataSelected = oTable.fnGetData(iDataIndex);
	if(aDataSelected == null) return;
	showDialogUrl(baseUrl + "/admin/module/edit","Cập nhật module",500);
}
function reLoadData(){
	oTable.fnDraw(false);
}
$(document).ready(function(){
	$(document).delegate("#btXoa:not(.deactive)","click",function(){
		dataString = '';
		$("#dataTable tbody input[type=checkbox]:checked").each(function(){
			dataString+='&id[]='+this.value;
		});
		if(dataString == '') {
			alert('Bạn chưa chọn hình ảnh cần xóa!');
			return;
		}
		if(!confirm('Bạn muốn xóa những hình ảnh đã chọn?'))
			return;
		$("#btXoa").addClass("deactive").find('span').text("Đang xóa...");
		$.ajax({
			type: "GET",
			cache: false,
			url : baseUrl+'/admin/slide/delete',
			data: dataString,
			success: function(data){
				$("#btXoa").removeClass("deactive").find('span').text("Xóa");
				if(data.rs == 'ERROR') {
					ajax_error(data.data);
				} else {
					oTable.fnDraw(false);
				}
			},
			error: function(data){ alert (data);$("#btXoa").removeClass("deactive").find('span').text("Xóa");}	
		});	
	});
	$(document).delegate("#btHide:not(.deactive)","click",function(){
		var button = $(this);
		var dataString = '';
		$("#dataTable tbody input[type=checkbox]:checked").each(function(){
			dataString+='&id[]='+this.value;
		});
		if(dataString == '') {
			alert('Bạn chưa chọn hình ảnh cần ẩn!');
			return;
		}
		if(!confirm('Bạn muốn ẩn những hình ảnh đã chọn?'))
			return;
		button.addClass("deactive").find('span').text("Đang xử lý...");
		$.ajax({
			type: "GET",
			cache: false,
			url : baseUrl+'/admin/slide/update-state?state=0',
			data: dataString,
			success: function(data){
				button.removeClass("deactive").find('span').text("Ẩn");
				if(data.rs == 'ERROR') {
					ajax_error(data.data);
				} else {
					oTable.fnDraw(false);
				}
			},
			error: function(data){}	
		});	
	});
	$(document).delegate("#btShow:not(.deactive)","click",function(){
		var button = $(this);
		var dataString = '';
		$("#dataTable tbody input[type=checkbox]:checked").each(function(){
			dataString+='&id[]='+this.value;
		});
		if(dataString == '') {
			alert('Bạn chưa chọn hình ảnh cần hiển thị!');
			return;
		}
		button.addClass("deactive").find('span').text("Đang xử lý...");
		$.ajax({
			type: "GET",
			cache: false,
			url : baseUrl+'/admin/slide/update-state?state=1',
			data: dataString,
			success: function(data){
				button.removeClass("deactive").find('span').text("Hiển thị");
				if(data.rs == 'ERROR') {
					ajax_error(data.data);
				} else {
					oTable.fnDraw(false);
				}
			},
			error: function(data){}	
		});	
	});
	oTable = $('#dataTable').dataTable({
		'iDisplayLength': 100,
		"bJQueryUI": true,
		"bProcessing": true,
		"bScrollCollapse": true,
		"bServerSide": true,
		"bAutoWidth": false,
		"sAjaxSource": baseUrl+'/admin/slide/list',
		"aoColumns": [
					{ "mDataProp": null,"bSortable": false,"fnRender" : function(oObj) { return oObj.iDataRow+1}},
					{ "mDataProp": "id","bSortable": false,"sClass":"hidden"},
					{ 	"mDataProp": null,"bSortable": false,
						"fnRender": function( oObj ) {
							if(oObj.aData.image_url == '') {
								return 'Không có hình ảnh';
							} else {
								return '<img alt='+oObj.aData.filename+'"" src="'+baseUrl + oObj.aData.thumb +'" height="70"/>';
							}
						}
					},
					{ "mDataProp": "stt","bSortable": false,"sClass":"td_center td_stt"},
					{ 	"mDataProp": null,"bSortable": false,"sClass": "td_center",
						"fnRender": function( oObj ) {
							if(oObj.aData.state == '1') {
								return 'Hiển thị';
							} else if(oObj.aData.state == '0') {
								return 'Ẩn';
							}
						}
					},
					{ 	"mDataProp": null,"bSortable": false,
						"fnRender": function( oObj ) {
							return '<center><input type="checkbox" onclick="doCheck('+oObj.iDataRow+')" value="'+oObj.aData.id+'"/></center>'; 
						}
					}
				],
		"fnServerData": function ( sSource, aoData, fnCallback ) {
			$.ajax( {
				"dataType": 'json', 
				"type": "POST", 
				"url": sSource, 
				"data": aoData, 
				"success": function(data){
					if(data.rs == 'ERROR') {
						ajax_error(data.data);
					} else {
						fnCallback(data);
					}
				}
			} );
		},
		"fnDrawCallback": function () {
			$('#dataTable .td_stt').editable( baseUrl + '/admin/slide/update-position', {
				"callback": function( response, y ) {
					response = $.parseJSON(response);
					if(response.rs == 'ERROR') {
						ajax_error(response.data);
					} else {
						var aPos = oTable.fnGetPosition( this );
						oTable.fnUpdate( response.data, aPos[0], aPos[1] );
					}
				},
				"submitdata": function ( value, settings ) {
					return {
						"row_id": $.trim($(this.parentNode.cells[1]).text()),
						"column": oTable.fnGetPosition( this )[2]
					};
				},
				"height": "14px"
			} );
		},
		"sPaginationType": "two_button"
	});
});
</script>