<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<?php
$actual_link = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
$baseUrl = $this->baseUrl();
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="<?php echo $baseUrl?>/favico.ico">
<title>TRASFER</title>
<meta http-equiv="content-language" content="vi"/>
<meta content="Vietnamese, Vietnam" name="language">
<link rel="stylesheet" href="<?php echo $baseUrl?>/css/front_style.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $baseUrl?>/css/jquery-ui.css" type="text/css" media="screen" />
</head>
<body>
	<ul>
	<?php
	foreach($this->data as $key => $value) {
		echo '<li id="'.$key.'">'.$value.'</li>'; 
	}
	?>
	</ul>
</body>
</html>