<?php
$baseUrl = $this->baseUrl();
?>
<!--[if lt IE 8]><style>
.wraptocenter span {
    display: inline-block;
    height: 100%;
}
</style><![endif]-->
<?php echo $this->render('/templates/left.phtml')?>
<div id="right_col">
	<h1 style="text-align: left; border-bottom: 1px dashed gray; margin-bottom: 5px; padding-bottom: 10px;">Rao vặt về làm thêm</h1>
	<?php
	foreach($this->list as $item) {
		echo $this->partial('/templates/list-raovat.phtml',array('data'=>$item,'baseUrl' => $baseUrl));
	}
	echo $this->partial('/templates/paging.phtml',array(
		'link' => $baseUrl.'/rao-vat?',
		'baseUrl' => $baseUrl,
		'pagesindex' => $this->page,
		'pageend' => $this->totalPage
	));
	?>
</div>
</div>
<script>
$(document).ready(function(){
	$("abbr.timeago").timeago();
	$('input[placeholder], textarea[placeholder]').placeholder();
	$("div.row").live("hover",function(event){
		if( event.type === 'mouseenter' ) {
			$(this).css("background-color","lightyellow");
		} else {
			$(this).css("background-color","");
		}
	});
});
</script>