<?php $baseUrl = $this->baseUrl()?>
<div id="left_col">
	<div class="block">
	<a class="logo" style="text-decoration: none; text-align: center;" href="<?php echo $baseUrl ?>/"/><img style="border: medium none; " src="<?php echo $baseUrl ?>/images/logo.png" alt="logo"/>
				<span class="slogan">Mạng xã hội việc làm Việt Nam</span></a>
	</div>
	<div class="block">
		<span class="block_title">Tag nổi bật </span>
		<?php echo $this->render('/templates/top-tag.phtml')?>
	</div>
</div>