<div class="small_box_container">
	<div class="header">HỖ TRỢ TRỰC TUYẾN</div>
	<div class="content">
		<p class="p_online">HỖ TRỢ KINH DOANH</p>
		<div class="div_support_online">
			<a class="link" href="ymsgr:sendim?hotro2.gianhangvn">
				<img src="http://opi.yahoo.com/online?u=hotro2.gianhangvn&amp;t=5" title="Mr. Minh" alt="">
				<span class="s_name">Kinh doanh 1 - 093 3.175.490</span> </a>
		</div>
		<p class="p_online">HỖ TRỢ KỸ THUẬT</p>
		<div class="div_support_online">
			<a class="link" href="ymsgr:sendim?hotro2.gianhangvn">
				<img src="http://opi.yahoo.com/online?u=hotro2.gianhangvn&amp;t=5" title="Mr. Minh" alt="">
				<span class="s_name">Kỹ thuật 1 - 093 3.175.490</span> </a>
		</div>
	</div>
</div>