<ul style="text-align: left;">
<?php
$list = Application_Model_DbTable_Article::findTopNews();
foreach($list as $item) {
	echo '<li> - <a href="'.$this->baseUrl().Core_Utils_Tools::genArticleUrl($item).'" title="'.$item['title'].'">'.Core_Utils_String::trim($item['title'],25).'</a></li>';
}
?>
<li style="text-align: left; margin-top: 5px;"><a href="<?php echo $this->baseUrl()?>/tintuc">Xem thêm...</a></li>
</ul>