<?php
$baseUrl = $this->baseUrl();
?>
<?php echo $this->render('/templates/left.phtml')?>
<div id="right_col">
	<div class="ui-state-error ui-corner-all" style="padding: 0px 0.7em; margin-top: 10px;">
		<p style="padding: 3px; text-align: left; margin: 0px;"><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
		<strong>Lỗi : </strong> <?php echo $this->error_msg?></p>
	</div>
</div>
