<?php
$baseUrl = $this->baseUrl();
?>
<?php echo $this->render('/templates/left.phtml')?>
<div id="right_col">
	<div class="ui-state-highlight ui-corner-all" style=" padding: 0px 0.7em; margin-top: 10px;">
		<p style="padding: 3px; text-align: left; margin: 0px;"><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
		<strong>Chào bạn! </strong> Bạn đã đăng tin tuyển dụng thành công.</p>
	</div>
	<span style="text-align: left; display: block; margin-top: 5px; ">Chúng tôi vừa gửi một email xác nhận đến địa chỉ mail <strong style="color: orangered;"><?php echo $this->email?></strong>, vui lòng check mail để xác nhận, sau khi xác nhận thành công thì tin đăng của bạn sẽ được hiển thị trên trang chủ.</span>
</div>