<?php
$baseUrl = $this->baseUrl();
?>
<?php echo $this->render('/templates/left.phtml')?>
<div id="right_col">
	<div class="ui-state-highlight ui-corner-all" style=" padding: 0px 0.7em; margin-top: 10px;">
		<p style="padding: 3px; text-align: left; margin: 0px;"><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
		<strong>Chào bạn! </strong> Bạn đã hủy đăng tin tuyển dụng thành công.</p>
	</div>
	<span style="text-align: left; display: block; margin-top: 5px; ">Chúng tôi đã hủy tin tuyển dụng vừa rồi trên trang web jobbid.vn, thành thật xin lỗi vì đã làm phiền bạn.</span>
</div>